In [1]:
import numpy as np
print(np.__version__)


2.3.5


In [2]:
# array

data=np.array(23)
print(type(data))
print(data.shape)

#1D Array

my_list=[12,13,14,15,16,17,18,19]

data=np.array(my_list)
print(data)
print(data.ndim)

<class 'numpy.ndarray'>
()
[12 13 14 15 16 17 18 19]
1


In [3]:
#2D

data_2d = np.array([
    [21,22,23],
    [24,25,26],
    [27,28,29]
])

print(data_2d)
print(data_2d.ndim)
print(data_2d.shape)

[[21 22 23]
 [24 25 26]
 [27 28 29]]
2
(3, 3)


In [4]:
# 2D array 4,5

data_three_array=([21,22,23,24,25],
                  [26,27,28,29,30],
                  [31,32,33,34,35],
                  [36,37,38,39,40])

data = np.array(data_three_array)
print(data)
print(data.ndim)
print(data.shape)

[[21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]
 [36 37 38 39 40]]
2
(4, 5)


In [5]:
#3D array

data_3d = np.array(
[                   
 [                  [12,13,14],
                    [15,16,17],
                    [18,19,20]
 ],
 [

                    [21,22,23],
                    [24,25,26],
                    [27,28,29]
 ]
]
    )



print(data_3d)
print(data_3d.size)
print(data_3d.shape)

[[[12 13 14]
  [15 16 17]
  [18 19 20]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
18
(2, 3, 3)


In [6]:
data_4d = np.array([
    [
        [
            [1, 2],
            [3, 4]
        ],
        [
            [5, 6],
            [7, 8]
        ]
    ],
    [
        [
            [9, 10],
            [11, 12]
        ],
        [
            [13, 14],
            [15, 16]
        ]
    ]
])

print(data_4d)
print(data_4d.size)
print(data_4d.shape)
print(data_4d.ndim)

[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
16
(2, 2, 2, 2)
4
