In [1]:
import numpy as np

In [2]:
from numpy import random

In [3]:
x = random.randint(100)
print(x)

31


In [4]:
x = random.rand()
print(x)

0.6160515785558955


In [5]:
x = random.randint(100,size=(3,5))
print(x)

[[22 17 37 63 79]
 [52  0 88 45 20]
 [57 11 42 58 91]]


In [6]:
# Float Array
x = random.rand(5)
print(x)

#Create 2D Array
x = random.rand(3,5)
print(x)

[0.65414931 0.1746282  0.84787734 0.64615715 0.49511419]
[[0.27357414 0.04195838 0.81318659 0.52740684 0.54165329]
 [0.12860266 0.93784498 0.8860334  0.43333695 0.79431732]
 [0.31551675 0.63340368 0.50031137 0.35555296 0.08125087]]


In [7]:
#Single Value
x = random.choice([3,4,5,6,7,8,9,10])
print(x)

8


In [8]:
# Array of values 2d array
x = random.choice([1,2,3,4,5,6,7,8,9],size=(3,3))
print(x)

[[4 4 1]
 [6 1 9]
 [1 9 7]]


In [9]:
colour = ["red","green","blue","lightgreen","pink"]
selected = np.random.choice(colour,size=3)
print(selected)

['green' 'lightgreen' 'green']


In [10]:
#Shuffle in array
arr = np.array([21,22,23,24,25])
np.random.shuffle(arr)

#permuation
new_arr = np.random.permutation(arr)
print(new_arr)

[23 22 21 25 24]


In [11]:
#Seed()
np.random.seed(42)
x = np.random.randint(1,100)
print(x)

52
