In [1]:
import numpy as np
data = np.array([12,13,14,15,16,17])
print(data[3])
print(data[-2])

#SLicing
print(data[1:4])
print(data[:4])
print(data[2:])
print(data[:])

15
16
[13 14 15]
[12 13 14 15]
[14 15 16 17]
[12 13 14 15 16 17]


In [2]:
data_2d = np.array([
    [21,22,23],
    [24,25,26],
    [27,28,29]
])

print(data_2d)
print(data_2d.ndim)
print(data_2d.shape)

print(data_2d[1,1])
print(data_2d[0,1])

#access 2nd column

print(data_2d[:,1])
print(data_2d[0,:])

[[21 22 23]
 [24 25 26]
 [27 28 29]]
2
(3, 3)
25
22
[22 25 28]
[21 22 23]


In [3]:
arr_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_3d)

#Ellipsis (...)
print(arr_3d[...,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 3]
 [5 7]]


In [4]:
print(arr_3d[...,1])

[[2 4]
 [6 8]]


In [5]:
print(arr_3d[1][0,1]) #remove single number

6


In [6]:
print(arr_3d[0][1,:])

[3 4]


In [7]:
print(arr_3d[1][1,:])

[7 8]


In [8]:
#reshape()

data = np.array([11,12,13,14,15,16])
new_r = data.reshape(2,3)
print(new_r)

[[11 12 13]
 [14 15 16]]
